exports.message = {
  required_fields: "Required fields are empty",
  success: "Success",
  fail: "Fail",
  product_not_created: "Product not created",
  INVALID_USER: "Invalid user credentials",
  SUCESS_MESSAGE: "Success",
  USER_LOGGED_SUCCESS: "User logged in successfully",
  BEARER: "Bearer",
  FAIL_MESSAGE: "Failed",
  ERROR: "Error",
  NO_TOKEN: "No token provided",
  SIGN_IN: "Invalid token format. Please sign in to get access.",
  USER_NOT_EXIST: "User does not exist or account is not active",
  ERROR: "Error",
  FAIL_MESSAGE: "Failed",
};
